name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*' # e.g. v0.1.0, v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@CodeGoat-dev'

      - name: Install dependencies
        run: npm install

      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
